# Generated by Django 4.2.4 on 2023-09-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calories',
            field=models.CharField(default='', max_length=365),
        ),
        migrations.AddField(
            model_name='profile',
            name='protein',
            field=models.CharField(default='', max_length=365),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.CharField(default='', max_length=365),
        ),
    ]
