# Generated by Django 4.2.4 on 2023-09-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_calories_profile_protein_profile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calories',
            field=models.CharField(default='0', max_length=365),
        ),
        migrations.AlterField(
            model_name='profile',
            name='protein',
            field=models.CharField(default='0', max_length=365),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.CharField(default='0', max_length=365),
        ),
    ]
