# Generated by Django 4.2.4 on 2023-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_calories_alter_profile_protein_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='calories',
            field=models.CharField(default='', max_length=365),
        ),
        migrations.AlterField(
            model_name='profile',
            name='protein',
            field=models.CharField(default='', max_length=365),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.CharField(default='', max_length=365),
        ),
    ]
