# Generated by Django 4.1.3 on 2023-09-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_remove_graphdata_label_remove_graphdata_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdata',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
