# Generated by Django 4.2.4 on 2023-09-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_remove_graphdata_data_graphdata_calories_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphData',
        ),
    ]
