# Generated by Django 4.1.3 on 2023-09-04 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphData',
        ),
    ]
