# Generated by Django 4.1.3 on 2023-09-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphdata',
            name='user',
        ),
    ]
