# Generated by Django 4.1.3 on 2023-09-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_remove_graphdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphdata',
            name='label',
        ),
        migrations.RemoveField(
            model_name='graphdata',
            name='value',
        ),
        migrations.AddField(
            model_name='graphdata',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
