# Generated by Django 4.1.3 on 2023-09-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_alter_graphdata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdata',
            name='data',
            field=models.CharField(max_length=365),
        ),
    ]
